- hosts: all
  become: true
  become_method: sudo
  vars:
    number_of_sessions: "{{ number_of_sessions | default(1) }}"
  tasks:
  - name: Apt Update
    ansible.builtin.apt:
      update_cache: true
      autoremove: true

  - name: Install required packages
    ansible.builtin.apt:
      pkg:
        - novnc
        - tigervnc-standalone-server
        - websockify
        - nginx

  - name: Create .vnc directory 
    file: 
      state: directory
      path: /home/vagrant/.vnc
      owner: vagrant
      group: vagrant

  - name: Create tigervnc configuration file
    copy:
      dest: "/home/vagrant/.vnc/xstartup"
      src: "./xstartup"
      owner: vagrant
      group: vagrant
      mode: 0755
  
  - name: Start a XVNC Server
    ansible.builtin.shell: |
      for i in $(seq 1 {{ number_of_sessions }} ); do
        vncserver -SecurityTypes none -xstartup /home/vagrant/.vnc/xstartup
        websockify -D --web /usr/share/novnc/ $((8000+i)) localhost:$((5900+i))
      done;
    args:
      executable: /bin/bash
    
  # Might be cool to have this run my dotfiles
  # Another option is to have vncserver run as vagrant user instead of root
